//定义了Rattitude模式下，油门的阈值
PARAM_DEFINE_FLOAT(XHY_RATT_TH, 0.8f);

//定义了位置控制，非线性动态逆的两个控制参数，Am1是角度环，Am2是角速率环
PARAM_DEFINE_FLOAT(AM1_OUTER, 2.7f);

PARAM_DEFINE_FLOAT(AM2_OUTER, 8.0f);

//定义飞行器的三轴转动惯量的先验知识，单位为国际单位kg*m^2
PARAM_DEFINE_FLOAT(IXX, 0.025f);

PARAM_DEFINE_FLOAT(IYY, 0.07f);

PARAM_DEFINE_FLOAT(IZZ, 0.022f);



//定义低通滤波器的系数，也反应了带宽的选取
PARAM_DEFINE_FLOAT(LOWPASSFILTER, 30.0f);

//定义和控制分配有关的几个变量
PARAM_DEFINE_FLOAT(CONTROL_AL1, 0.0f);
PARAM_DEFINE_FLOAT(CONTROL_AL2, 0.0f);
PARAM_DEFINE_FLOAT(CONTROL_AL3, 0.0f);
PARAM_DEFINE_FLOAT(CONTROL_AL4, 0.0f);
PARAM_DEFINE_FLOAT(CONTROL_AL5, 0.0f);
PARAM_DEFINE_FLOAT(CONTROL_AL6, 0.0f);
PARAM_DEFINE_FLOAT(CONTROL_AL7, 0.0f);
PARAM_DEFINE_FLOAT(CONTROL_AL8, 0.0f);


//SW里面的一些参数设置
PARAM_DEFINE_FLOAT(EPSIONW, 1e-5f);
PARAM_DEFINE_FLOAT(EPSIONTHETA, 1e-5f);
PARAM_DEFINE_FLOAT(EPSIONSIGMA, 1e-5f);
PARAM_DEFINE_FLOAT(DELTAW, 2.0f);
PARAM_DEFINE_FLOAT(DELTATHETA, 0.11f);
PARAM_DEFINE_FLOAT(DELTASIGMA, 0.11f);

//P，是李雅普诺夫方程Am2×P+P×Am2'+Q = 0的解
PARAM_DEFINE_FLOAT(P11, 0.0625f);
PARAM_DEFINE_FLOAT(P22, 0.0625f);
PARAM_DEFINE_FLOAT(P33, 0.0625f);

//下面这三个变量反应了这个公式，其实就是kg -inv(inv(Am2)*inv([Ixx 0 0;0 Iyy 0;0 0 Izz]))
PARAM_DEFINE_FLOAT(KG1, 0.2f);
PARAM_DEFINE_FLOAT(KG2, 0.04f);
PARAM_DEFINE_FLOAT(KG3, 0.176f);
